packages:
  - apps/*
  - packages/*
nodeLinker: hoisted
patchedDependencies:
  '@noble/hashes@1.8.0': patches/@noble__hashes@1.8.0.patch
  '@noble/hashes@1.3.2': patches/@noble__hashes@1.3.2.patch
  multiformats@9.9.0: patches/multiformats@9.9.0.patch
  '@reown/appkit-adapter-ethers@1.8.19': patches/@reown__appkit-adapter-ethers@1.8.19.patch
  '@reown/appkit-utils@1.8.19': patches/@reown__appkit-utils@1.8.19.patch
